<a href="https://colab.research.google.com/github/ratansen/Numerical-Methods-using-Python/blob/main/linear_equations/Cholesky_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cholesky Decomposition Using a 4x4 Matrix

Cholesky decomposition is a numerical method used to decompose a positive-definite matrix into a product of a lower triangular matrix and its transpose. This decomposition is particularly useful in solving linear systems, optimizing algorithms, and in Monte Carlo simulations. To illustrate the Cholesky decomposition, let's consider a 4x4 positive-definite matrix $ A $.

## Matrix $ A $
Suppose $ A $ is given by:

$
A = \begin{pmatrix}
4 & 12 & -16 & 0 \\
12 & 37 & -43 & 0 \\
-16 & -43 & 98 & 0 \\
0 & 0 & 0 & 25
\end{pmatrix}
$

The Cholesky decomposition of $ A $ involves finding a lower triangular matrix $ L $ such that:

$
A = L L^T
$

Where $ L $ is a 4x4 lower triangular matrix:

$
L = \begin{pmatrix}
l_{11} & 0 & 0 & 0 \\
l_{21} & l_{22} & 0 & 0 \\
l_{31} & l_{32} & l_{33} & 0 \\
l_{41} & l_{42} & l_{43} & l_{44}
\end{pmatrix}
$

## Steps to Compute $ L $

1. **Compute $ l_{11} $:**

$
l_{11} = \sqrt{a_{11}} = \sqrt{4} = 2
$

2. **Compute the first column of $ L $:**

$
l_{21} = \frac{a_{21}}{l_{11}} = \frac{12}{2} = 6
$

$
l_{31} = \frac{a_{31}}{l_{11}} = \frac{-16}{2} = -8
$

$
l_{41} = \frac{a_{41}}{l_{11}} = \frac{0}{2} = 0
$

3. **Compute $ l_{22} $:**

$
l_{22} = \sqrt{a_{22} - l_{21}^2} = \sqrt{37 - 6^2} = \sqrt{37 - 36} = 1
$

4. **Compute the second column of $ L $:**

$
l_{32} = \frac{a_{32} - l_{31}l_{21}}{l_{22}} = \frac{-43 - (-8) \cdot 6}{1} = \frac{-43 + 48}{1} = 5
$

$
l_{42} = \frac{a_{42} - l_{41}l_{21}}{l_{22}} = \frac{0 - 0 \cdot 6}{1} = 0
$

5. **Compute $ l_{33} $:**

$
l_{33} = \sqrt{a_{33} - l_{31}^2 - l_{32}^2} = \sqrt{98 - (-8)^2 - 5^2} = \sqrt{98 - 64 - 25} = \sqrt{9} = 3
$

6. **Compute the third column of $ L $:**

$
l_{43} = \frac{a_{43} - l_{41}l_{31} - l_{42}l_{32}}{l_{33}} = \frac{0 - 0 \cdot (-8) - 0 \cdot 5}{3} = 0
$

7. **Compute $ l_{44} $:**

$
l_{44} = \sqrt{a_{44} - l_{41}^2 - l_{42}^2 - l_{43}^2} = \sqrt{25 - 0^2 - 0^2 - 0^2} = \sqrt{25} = 5
$

## Lower Triangular Matrix $ L $

After computing all the elements, the matrix $ L $ is:

$
L = \begin{pmatrix}
2 & 0 & 0 & 0 \\
6 & 1 & 0 & 0 \\
-8 & 5 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix}
$

Thus, the Cholesky decomposition of $ A $ is:

$
A = L L^T = \begin{pmatrix}
2 & 0 & 0 & 0 \\
6 & 1 & 0 & 0 \\
-8 & 5 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix}
\begin{pmatrix}
2 & 6 & -8 & 0 \\
0 & 1 & 5 & 0 \\
0 & 0 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix}
$

In [ ]:
import numpy as np
from pprint import pprint

In [ ]:
N = 4  # dimension
A = np.array([[4, 12, -16, 0],
                        [12, 37, -43, 0],
                        [-16, -43, 98, 0],
                        [0, 0, 0, 25]
                        ])

In [ ]:
def cholesky(A):
  n = len(A)
  L = np.array([[0.0] * n for  i in range(n)])
  for i in range(n):
      for k in range(i+1):
          tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))

          if (i == k): # Diagonal elements
              L[i][k] = np.sqrt(A[i][i] - tmp_sum)
          else:
              L[i][k] = (1.0 / L[k][k]) * ((A[i][k] - tmp_sum))
  return L

In [ ]:
L = cholesky(A)
pprint(L)

array([[ 2.,  0.,  0.,  0.],
       [ 6.,  1.,  0.,  0.],
       [-8.,  5.,  3.,  0.],
       [ 0.,  0.,  0.,  5.]])


In [ ]:
# verify
W = np.matmul(L, L.T)
print(W)
print(A)
print("Diff : \n", W - A)

[[  4.  12. -16.   0.]
 [ 12.  37. -43.   0.]
 [-16. -43.  98.   0.]
 [  0.   0.   0.  25.]]
[[  4  12 -16   0]
 [ 12  37 -43   0]
 [-16 -43  98   0]
 [  0   0   0  25]]
Diff : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##Solving linear equation using Cholesky Decomposition
To solve a linear system $ A \mathbf{x} = \mathbf{b} $ using the Cholesky decomposition, we utilize the fact that $ A $ can be decomposed into $ L L^T $. This allows us to transform the problem into two simpler systems of equations that can be solved sequentially.

Given the matrix $ A $ and its Cholesky decomposition $ A = L L^T $, and the equation:

$ A \mathbf{x} = \mathbf{b} $

We proceed as follows:

1. **Solve $ L \mathbf{y} = \mathbf{b} $ for $ \mathbf{y} $ (forward substitution)**

2. **Solve $ L^T \mathbf{x} = \mathbf{y} $ for $ \mathbf{x} $ (backward substitution)**

Let's solve this with an example where:

$ A = \begin{pmatrix}
4 & 12 & -16 & 0 \\
12 & 37 & -43 & 0 \\
-16 & -43 & 98 & 0 \\
0 & 0 & 0 & 25
\end{pmatrix} $

$ L = \begin{pmatrix}
2 & 0 & 0 & 0 \\
6 & 1 & 0 & 0 \\
-8 & 5 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix} $

Suppose we have:

$ \mathbf{b} = \begin{pmatrix}
1 \\
2 \\
3 \\
4
\end{pmatrix} $

### Step 1: Solve $ L \mathbf{y} = \mathbf{b} $

$ \begin{pmatrix}
2 & 0 & 0 & 0 \\
6 & 1 & 0 & 0 \\
-8 & 5 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix} \begin{pmatrix}
y_1 \\
y_2 \\
y_3 \\
y_4
\end{pmatrix} = \begin{pmatrix}
1 \\
2 \\
3 \\
4
\end{pmatrix} $

This gives us a system of equations:

1. $ 2y_1 = 1 \Rightarrow y_1 = \frac{1}{2} = 0.5 $
2. $ 6y_1 + y_2 = 2 \Rightarrow 6 \cdot \frac{1}{2} + y_2 = 2 \Rightarrow 3 + y_2 = 2 \Rightarrow y_2 = -1 $
3. $ -8y_1 + 5y_2 + 3y_3 = 3 \Rightarrow -8 \cdot \frac{1}{2} + 5 \cdot (-1) + 3y_3 = 3 \Rightarrow -4 - 5 + 3y_3 = 3 \Rightarrow 3y_3 = 12 \Rightarrow y_3 = 4 $
4. $ 5y_4 = 4 \Rightarrow y_4 = \frac{4}{5} = 0.8 $

So, we have:

$ \mathbf{y} = \begin{pmatrix}
0.5 \\
-1 \\
4 \\
0.8
\end{pmatrix} $

### Step 2: Solve $ L^T \mathbf{x} = \mathbf{y} $

$ \begin{pmatrix}
2 & 6 & -8 & 0 \\
0 & 1 & 5 & 0 \\
0 & 0 & 3 & 0 \\
0 & 0 & 0 & 5
\end{pmatrix} \begin{pmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{pmatrix} = \begin{pmatrix}
0.5 \\
-1 \\
4 \\
0.8
\end{pmatrix} $

This gives us a system of equations:

1. $ 5x_4 = 0.8 \Rightarrow x_4 = 0.16 $
2. $ 3x_3 = 4 \Rightarrow x_3 = 1.333 $
3. $ x_2 + 5x_3 = -1 \Rightarrow x_2 = -7.666 $
4. $ 2x_1 + 6x_2 - 8x_3 = 0.5 \Rightarrow x_1 = 28.5833 $

So, we have:

$ \mathbf{x} = \begin{pmatrix}
28.5833 \\
-7.666 \\
1.333 \\
0.16
\end{pmatrix} $

Thus, the solution to the linear system $ A \mathbf{x} = \mathbf{b} $ is:

$ \mathbf{x} = \begin{pmatrix}
28.5833 \\
-7.666 \\
1.333 \\
0.16
\end{pmatrix} $

In [ ]:
def fwdsub(l, b):
    n = len(l[0])
    y = b
    for i in range(n):
        for j in range(i):
            y[i] -= l[i][j]*y[j]
        y[i] /= l[i][i]
    return y

def backsub(u, y):
    n = len(u[0])
    x = np.zeros(n)
    for i in range(1,n+1):
        x[-i] = y[-i]
        for j in range(1,i):
            x[-i] -= u[-i][-j]*x[-j]
        x[-i] /= u[-i][-i]
    return np.array([x]).T


In [ ]:
b = np.array([[1.0], [2.0], [3.0], [4.0]])
Y = fwdsub(L, b)
print("Y \n", Y)
U = np.transpose(L)
X = backsub(U, Y)
print("X \n", X)


Y 
 [[ 0.5]
 [-1. ]
 [ 4. ]
 [ 0.8]]
X 
 [[28.58333333]
 [-7.66666667]
 [ 1.33333333]
 [ 0.16      ]]


<ipython-input-28-7c727391263f>:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[-i] = y[-i]
