<a href="https://colab.research.google.com/github/ratansen/Numerical-Methods-using-Python/blob/main/linear_equations/Jacobi_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jacobi Method

## Jacobi Method for Eigenvalues and Eigenvectors

The method is named after Carl Gustav Jacob Jacobi, who first proposed the method in 1846.

- Iterative method for calculating the eigenvalues and corresponding eigenvectors of a real symmetric matrix.
- Adopts the process of matrix diagonalization, where the eigenvalues are equal to the diagonal element.
- A solution is guaranteed for all real symmetric matrixes.
- It is based on series of rotations called Jacobi or given rotations.
- The rotations that are similarity transformations are chosen to discard the off-diagonal elements in such a way that eigenvalues are preserved.

In this method, we will apply similarity transformations on the given matrix such that after a sequence of a
similarity transformations the matrix converts into a diagonal matrix and from the diagonal matrix, we can see the
eigenvalue directly as the diagonal element.

In [1]:
#importing libraries

import numpy as np
from numpy import array, identity, diagonal
import math
from math import sqrt
import sys
from pprint import pprint
import matplotlib.pyplot as plt

maxitr = 200
tol = 1.0e-9

In [4]:
A = np.array([[4, 2, 2, 1],
[2, -3, 1, 1],
[2, 1, 3, 1],
[1, 1, 1, 2]], float)
pprint(A)

n = len(A)

array([[ 4.,  2.,  2.,  1.],
       [ 2., -3.,  1.,  1.],
       [ 2.,  1.,  3.,  1.],
       [ 1.,  1.,  1.,  2.]])


In [5]:
n = len(A)

D = np.zeros((n,n))
D = np.copy(A)

for i in range(maxitr):
    for p in range(n):
        for q in range(p):
            if(abs(A[p][q])>tol):
                theta = (A[q][q]-A[p][p])/(2*A[p][q])
                t = theta/((abs(theta) + sqrt(theta*theta+1))*abs(theta))
                c = 1/(sqrt(t*t+1))
                s = c*t
                D[p][p] =((c**2)*A[p][p]) + ((s**2)*A[q][q]) - (2*c*s*A[p][q])
                D[q][q] = (s**2)*A[p][p] + (c**2)*A[q][q] + 2*c*s*A[p][q]
                D[p][q] = D[q][p] = 0
                for j in range(n):
                    if(j != p and j != q):
                        D[j][p] = (c*A[j][p])-(s*A[j][q])
                        D[p][j] = np.copy(D[j][p])
                        D[j][q] = c*A[j][q]+s*A[j][p]
                        D[q][j] = np.copy(D[j][q])
                A = np.copy(D)

for i in range(n):
    for j in range(n):
        if abs(A[i][j])<tol:
            A[i][j] = 0
print(diagonal(A))

[ 6.64575131 -3.64575131  1.35424869  1.64575131]


In [6]:
# Problem 2

# creating the matrix
n = 10
A = np.zeros((n,n))
D = np.zeros((n,n))
for i in range(n):
    A[i][i]=4
    if i+1<n:
        A[i+1][i] = A[i][i+1] = 2
    if i+2<n:
        A[i+2][i] = A[i][i+2] = 1
pprint(A)

array([[4., 2., 1., 0., 0., 0., 0., 0., 0., 0.],
       [2., 4., 2., 1., 0., 0., 0., 0., 0., 0.],
       [1., 2., 4., 2., 1., 0., 0., 0., 0., 0.],
       [0., 1., 2., 4., 2., 1., 0., 0., 0., 0.],
       [0., 0., 1., 2., 4., 2., 1., 0., 0., 0.],
       [0., 0., 0., 1., 2., 4., 2., 1., 0., 0.],
       [0., 0., 0., 0., 1., 2., 4., 2., 1., 0.],
       [0., 0., 0., 0., 0., 1., 2., 4., 2., 1.],
       [0., 0., 0., 0., 0., 0., 1., 2., 4., 2.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 4.]])


In [7]:
n = len(A)
D = np.copy(A)
for i in range(maxitr):
    for p in range(n):
        for q in range(p):
            if(abs(A[p][q])>tol):
                theta = (A[q][q]-A[p][p])/(2*A[p][q])
                if theta != 0:
                    t = theta/((abs(theta) + sqrt(theta*theta+1))*abs(theta))
                else:
                    t=1
                c = 1/(sqrt(t*t+1))
                s = c*t
                D[p][p] =((c**2)*A[p][p]) + ((s**2)*A[q][q]) - (2*c*s*A[p][q])
                D[q][q] = (s**2)*A[p][p] + (c**2)*A[q][q] + 2*c*s*A[p][q]
                D[p][q] = D[q][p] = 0
                for j in range(n):
                    if(j != p and j != q):
                        D[j][p] =(c*A[j][p])-(s*A[j][q])
                        D[p][j] = np.copy(D[j][p])
                        D[j][q] = c*A[j][q]+s*A[j][p]
                        D[q][j] = np.copy(D[j][q])
                A = np.copy(D)

pprint(np.around(diagonal(A), 6))

array([9.555026, 1.188039, 1.205693, 8.322571, 2.      , 6.580836,
       1.783996, 4.705394, 1.591039, 3.067407])
